raspberry_pi_host: 192.168.1.41
service_user: sensor
infrastructure_dir: "/etc/infrastructure"
docker_dir: "{{ infrastructure_dir }}/docker"
prometheus_dir: "{{ infrastructure_dir }}/prometheus"
file_mode: "u=rw,g=r,o=r"
directory_mode: "u=rwx,g=rx,o=rx"
prometheus_metrics_port: 9101
sensors_bin_url: "https://github.com/vzhurin/raspberry-pi-sensors/releases/download/{{ sensors_version }}/raspberry-pi-sensors-{{ sensors_version }}-linux-arm64"
sensors_version: 0.0.7
sensors_container_name: sensors
